name: Build web page

on:
  push:
    branches:
    - main
    paths:
    - "website/**"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master

    - name: 'Build'
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_ONLY: true
        BUILD_DIR: website
        TOKEN: ${{ secrets.TOKEN }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/public
